#!/usr/bin/env bash
# Uses while loop to print Best school 10 times
# and has if statement
x=0
while [ $x -lt 10 ]
do
    echo "Best School"
    if [[ $x -eq 8 ]]; then
        echo "Hi"
    fi
    x=$(( x + 1 ))
done
